"""initial schema (docs/07)

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-31 13:31:27.651108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    if is_pg:
        # pgvector — задел на шаг 3 (нечёткое сопоставление с каталогом, FR-CAT-02).
        # Колонка embedding добавляется отдельной миграцией, когда будет выбрана
        # модель эмбеддингов: её размерность зависит от модели.
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        # pg_trgm — быстрый неточный поиск по названию и номеру детали (docs/07 §4)
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("type IN ('owner','shipyard')", name='ck_organizations_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('impa_code', sa.String(length=64), nullable=True),
    sa.Column('issa_code', sa.String(length=64), nullable=True),
    sa.Column('oem_number', sa.String(length=128), nullable=True),
    sa.Column('maker', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('specs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('equipment', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('impa_code IS NOT NULL OR issa_code IS NOT NULL OR oem_number IS NOT NULL', name='ck_parts_has_identifier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parts_category', 'parts', ['category'], unique=False)
    op.create_index('ix_parts_impa_code', 'parts', ['impa_code'], unique=False)
    op.create_index('ix_parts_issa_code', 'parts', ['issa_code'], unique=False)
    op.create_index('ix_parts_oem_number', 'parts', ['oem_number'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("type IN ('marketplace','supplier','oem')", name='ck_suppliers_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_alternatives',
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('alt_part_id', sa.Uuid(), nullable=False),
    sa.Column('compatibility', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("compatibility IN ('full','partial','kit')", name='ck_part_alternatives_compat'),
    sa.CheckConstraint('part_id <> alt_part_id', name='ck_part_alternatives_not_self'),
    sa.ForeignKeyConstraint(['alt_part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'alt_part_id', name='uq_part_alternatives_pair')
    )
    op.create_index('ix_part_alternatives_part_id', 'part_alternatives', ['part_id'], unique=False)
    op.create_table('repair_infos',
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('repair_cost_estimate', sa.String(length=64), nullable=True),
    sa.Column('replace_cost_estimate', sa.String(length=64), nullable=True),
    sa.Column('repair_time', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("verdict IN ('repair','replace')", name='ck_repair_infos_verdict'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', name='uq_repair_infos_part')
    )
    op.create_table('supplier_offers',
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('lead_time', sa.String(length=128), nullable=True),
    sa.Column('stock_status', sa.String(length=16), nullable=True),
    sa.Column('deep_link', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("stock_status IN ('in','low','out')", name='ck_supplier_offers_stock'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_offers_part_id', 'supplier_offers', ['part_id'], unique=False)
    op.create_index('ix_supplier_offers_supplier_id', 'supplier_offers', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("role IN ('mechanic','supplier_manager','fleet_owner','expert','admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login', name='uq_users_login')
    )
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('vessels',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('imo', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'imo', name='uq_vessels_org_imo')
    )
    op.create_index('ix_vessels_organization_id', 'vessels', ['organization_id'], unique=False)
    op.create_table('scans',
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('client_scan_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("status IN ('queued','processing','done','needs_review','error')", name='ck_scans_status'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'client_scan_id', name='uq_scans_author_client_key')
    )
    op.create_index('ix_scans_author_id', 'scans', ['author_id'], unique=False)
    op.create_index('ix_scans_status', 'scans', ['status'], unique=False)
    op.create_index('ix_scans_vessel_id', 'scans', ['vessel_id'], unique=False)
    op.create_table('user_vessels',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'vessel_id')
    )
    op.create_table('photos',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("kind IN ('overview','nameplate','context')", name='ck_photos_kind'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photos_scan_id', 'photos', ['scan_id'], unique=False)
    op.create_table('recognitions',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('maker_detected', sa.String(length=255), nullable=True),
    sa.Column('oem_detected', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("status IN ('auto','confirmed','corrected','rejected')", name='ck_recognitions_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_recognitions_confidence'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_recognitions_scan')
    )
    op.create_index('ix_recognitions_part_id', 'recognitions', ['part_id'], unique=False)
    op.create_table('moderation_tasks',
    sa.Column('recognition_id', sa.Uuid(), nullable=False),
    sa.Column('expert_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('corrected_part_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("resolution IS NULL OR resolution IN ('confirmed','corrected','rejected')", name='ck_moderation_tasks_resolution'),
    sa.CheckConstraint("status IN ('pending','in_progress','resolved')", name='ck_moderation_tasks_status'),
    sa.ForeignKeyConstraint(['corrected_part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_tasks_expert_id', 'moderation_tasks', ['expert_id'], unique=False)
    op.create_index('ix_moderation_tasks_status', 'moderation_tasks', ['status'], unique=False)
    op.create_table('part_requests',
    sa.Column('recognition_id', sa.Uuid(), nullable=True),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('client_request_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("priority IN ('low','normal','urgent')", name='ck_part_requests_priority'),
    sa.CheckConstraint("status IN ('new','in_review','approved','rejected','ordered','received')", name='ck_part_requests_status'),
    sa.CheckConstraint('quantity > 0', name='ck_part_requests_quantity'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'client_request_id', name='uq_part_requests_client_key')
    )
    op.create_index('ix_part_requests_status', 'part_requests', ['status'], unique=False)
    op.create_index('ix_part_requests_vessel_id', 'part_requests', ['vessel_id'], unique=False)
    op.create_table('recognition_candidates',
    sa.Column('recognition_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('relevance BETWEEN 0 AND 1', name='ck_recognition_candidates_relevance'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recognition_candidates_recognition_id', 'recognition_candidates', ['recognition_id'], unique=False)
    op.create_table('training_samples',
    sa.Column('recognition_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('correct_part_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("source IN ('user_feedback','expert')", name='ck_training_samples_source'),
    sa.ForeignKeyConstraint(['correct_part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_samples_recognition_id', 'training_samples', ['recognition_id'], unique=False)
    # ### end Alembic commands ###

    if is_pg:
        op.execute("CREATE INDEX ix_parts_name_trgm ON parts USING gin (name gin_trgm_ops)")
        op.execute(
            "CREATE INDEX ix_parts_oem_number_trgm ON parts USING gin (oem_number gin_trgm_ops)"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_parts_oem_number_trgm")
        op.execute("DROP INDEX IF EXISTS ix_parts_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_samples_recognition_id', table_name='training_samples')
    op.drop_table('training_samples')
    op.drop_index('ix_recognition_candidates_recognition_id', table_name='recognition_candidates')
    op.drop_table('recognition_candidates')
    op.drop_index('ix_part_requests_vessel_id', table_name='part_requests')
    op.drop_index('ix_part_requests_status', table_name='part_requests')
    op.drop_table('part_requests')
    op.drop_index('ix_moderation_tasks_status', table_name='moderation_tasks')
    op.drop_index('ix_moderation_tasks_expert_id', table_name='moderation_tasks')
    op.drop_table('moderation_tasks')
    op.drop_index('ix_recognitions_part_id', table_name='recognitions')
    op.drop_table('recognitions')
    op.drop_index('ix_photos_scan_id', table_name='photos')
    op.drop_table('photos')
    op.drop_table('user_vessels')
    op.drop_index('ix_scans_vessel_id', table_name='scans')
    op.drop_index('ix_scans_status', table_name='scans')
    op.drop_index('ix_scans_author_id', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_vessels_organization_id', table_name='vessels')
    op.drop_table('vessels')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_supplier_offers_supplier_id', table_name='supplier_offers')
    op.drop_index('ix_supplier_offers_part_id', table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_table('repair_infos')
    op.drop_index('ix_part_alternatives_part_id', table_name='part_alternatives')
    op.drop_table('part_alternatives')
    op.drop_table('suppliers')
    op.drop_index('ix_parts_oem_number', table_name='parts')
    op.drop_index('ix_parts_issa_code', table_name='parts')
    op.drop_index('ix_parts_impa_code', table_name='parts')
    op.drop_index('ix_parts_category', table_name='parts')
    op.drop_table('parts')
    op.drop_table('organizations')
    # ### end Alembic commands ###
