"""scan pipeline: photo hash and vision cache

Revision ID: 0002_scan_pipeline
Revises: 0001_initial
Create Date: 2026-07-31 14:17:29.099789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_scan_pipeline'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_cache',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'image_sha256', name='uq_vision_cache_provider_image')
    )
    op.create_index('ix_vision_cache_created_at', 'vision_cache', ['created_at'], unique=False)
    op.add_column('photos', sa.Column('mime_type', sa.String(length=128), nullable=True))
    op.add_column('photos', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('content_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_photos_content_sha256'), 'photos', ['content_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_content_sha256'), table_name='photos')
    op.drop_column('photos', 'content_sha256')
    op.drop_column('photos', 'size_bytes')
    op.drop_column('photos', 'mime_type')
    op.drop_index('ix_vision_cache_created_at', table_name='vision_cache')
    op.drop_table('vision_cache')
    # ### end Alembic commands ###
