"""catalog matching: normalized codes, aliases, tokens

Revision ID: 0003_catalog_matching
Revises: 0002_scan_pipeline
Create Date: 2026-07-31 15:08:06.919870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003_catalog_matching'
down_revision: Union[str, None] = '0002_scan_pipeline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_aliases',
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('alias_norm', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'alias_norm', name='uq_part_aliases_part_alias')
    )
    op.create_index('ix_part_aliases_alias_norm', 'part_aliases', ['alias_norm'], unique=False)
    op.add_column('parts', sa.Column('impa_code_norm', sa.String(length=64), nullable=True))
    op.add_column('parts', sa.Column('issa_code_norm', sa.String(length=64), nullable=True))
    op.add_column('parts', sa.Column('oem_number_norm', sa.String(length=128), nullable=True))
    op.add_column('parts', sa.Column('maker_norm', sa.String(length=255), nullable=True))
    op.create_index('ix_parts_impa_norm', 'parts', ['impa_code_norm'], unique=False)
    op.create_index('ix_parts_issa_norm', 'parts', ['issa_code_norm'], unique=False)
    op.create_index('ix_parts_oem_norm', 'parts', ['oem_number_norm'], unique=False)
    op.add_column('recognitions', sa.Column('detected_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('recognitions', sa.Column('catalog_status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Нечёткий поиск должен доставать и по альтернативным написаниям (docs/07 §4)
        op.execute("CREATE INDEX ix_part_aliases_alias_trgm "
                   "ON part_aliases USING gin (alias_norm gin_trgm_ops)")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_part_aliases_alias_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recognitions', 'catalog_status')
    op.drop_column('recognitions', 'detected_tokens')
    op.drop_index('ix_parts_oem_norm', table_name='parts')
    op.drop_index('ix_parts_issa_norm', table_name='parts')
    op.drop_index('ix_parts_impa_norm', table_name='parts')
    op.drop_column('parts', 'maker_norm')
    op.drop_column('parts', 'oem_number_norm')
    op.drop_column('parts', 'issa_code_norm')
    op.drop_column('parts', 'impa_code_norm')
    op.drop_index('ix_part_aliases_alias_norm', table_name='part_aliases')
    op.drop_table('part_aliases')
    # ### end Alembic commands ###
