"""catalog: parts without codes allowed

Revision ID: 0004_parts_without_codes
Revises: 0003_catalog_matching
Create Date: 2026-07-31 15:15:59.831887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004_parts_without_codes'
down_revision: Union[str, None] = '0003_catalog_matching'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 30 из 56 позиций стартового каталога идут без публичных номеров (крупные
    # судовые дизели Wärtsilä, MAN B&W): их опознают по name/maker/equipment.
    # Требование «минимум один код» из docs/07 §3 снято, документ обновлён.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE parts DROP CONSTRAINT IF EXISTS ck_parts_has_identifier")
    else:
        # SQLite не умеет DROP CONSTRAINT — таблицу приходится пересоздавать
        with op.batch_alter_table("parts", recreate="always") as batch:
            batch.drop_constraint("ck_parts_has_identifier", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_parts_maker_norm', 'parts', ['maker_norm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE parts ADD CONSTRAINT ck_parts_has_identifier "
            "CHECK (impa_code IS NOT NULL OR issa_code IS NOT NULL OR oem_number IS NOT NULL)"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parts_maker_norm', table_name='parts')
    # ### end Alembic commands ###
