"""recognition feedback fields

Revision ID: 0006_recognition_feedback
Revises: 0005_parts_identifiable
Create Date: 2026-08-01 11:49:19.235657
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006_recognition_feedback'
down_revision: Union[str, None] = '0005_parts_identifiable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recognitions', sa.Column('feedback_verdict', sa.String(length=16), nullable=True))
    op.add_column('recognitions', sa.Column('feedback_by', sa.Uuid(), nullable=True))
    op.add_column('recognitions', sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recognitions', sa.Column('feedback_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # FK и CHECK: SQLite не умеет ALTER для ограничений — нужен batch-режим
    bind = op.get_bind()
    check = "feedback_verdict IS NULL OR feedback_verdict IN ('confirm','reject')"
    if bind.dialect.name == "postgresql":
        op.create_foreign_key("fk_recognitions_feedback_by", "recognitions", "users",
                              ["feedback_by"], ["id"], ondelete="SET NULL")
        op.execute(f"ALTER TABLE recognitions ADD CONSTRAINT "
                   f"ck_recognitions_feedback_verdict CHECK ({check})")
    else:
        with op.batch_alter_table("recognitions", recreate="always") as batch:
            batch.create_foreign_key("fk_recognitions_feedback_by", "users",
                                     ["feedback_by"], ["id"], ondelete="SET NULL")
            batch.create_check_constraint("ck_recognitions_feedback_verdict", check)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE recognitions DROP CONSTRAINT IF EXISTS "
                   "ck_recognitions_feedback_verdict")
        op.drop_constraint("fk_recognitions_feedback_by", "recognitions", type_="foreignkey")
    op.drop_column('recognitions', 'feedback_comment')
    op.drop_column('recognitions', 'feedback_at')
    op.drop_column('recognitions', 'feedback_by')
    op.drop_column('recognitions', 'feedback_verdict')
    # ### end Alembic commands ###
