"""supplier offers: source and reman type

Revision ID: 0007_supplier_offers
Revises: 0006_recognition_feedback
Create Date: 2026-08-01 12:21:04.874803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007_supplier_offers'
down_revision: Union[str, None] = '0006_recognition_feedback'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен только на время добавления колонки к существующим строкам
    op.add_column('supplier_offers', sa.Column('source', sa.String(length=16),
                                               nullable=False, server_default='curated'))
    op.add_column('supplier_offers', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.alter_column("supplier_offers", "source", server_default=None)
        op.execute("ALTER TABLE supplier_offers DROP CONSTRAINT IF EXISTS ck_supplier_offers_source")
        op.execute("ALTER TABLE supplier_offers ADD CONSTRAINT ck_supplier_offers_source "
                   "CHECK (source IN ('curated','demo','api'))")
        # Одно предложение на пару «деталь + поставщик»: повторная заливка обновляет,
        # а не плодит дубли
        op.create_unique_constraint("uq_supplier_offers_part_supplier", "supplier_offers",
                                    ["part_id", "supplier_id"])
        # Появился тип поставщика reman (восстановление) — расширяем CHECK
        op.execute("ALTER TABLE suppliers DROP CONSTRAINT IF EXISTS ck_suppliers_type")
        op.execute("ALTER TABLE suppliers ADD CONSTRAINT ck_suppliers_type "
                   "CHECK (type IN ('marketplace','supplier','oem','reman'))")
    else:
        with op.batch_alter_table("supplier_offers", recreate="always") as batch:
            batch.create_check_constraint("ck_supplier_offers_source",
                                          "source IN ('curated','demo','api')")
            batch.create_unique_constraint("uq_supplier_offers_part_supplier",
                                           ["part_id", "supplier_id"])
        with op.batch_alter_table("suppliers", recreate="always") as batch:
            batch.drop_constraint("ck_suppliers_type", type_="check")
            batch.create_check_constraint(
                "ck_suppliers_type", "type IN ('marketplace','supplier','oem','reman')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_offers', 'fetched_at')
    op.drop_column('supplier_offers', 'source')
    # ### end Alembic commands ###
